import { defineConfig } from 'vite-plus';

export default defineConfig({
  fmt: {
    singleQuote: true,
    jsxSingleQuote: false,
    semi: true,
    trailingComma: 'es5',
    printWidth: 80,
    tabWidth: 2,
    useTabs: false,
    arrowParens: 'always',
    bracketSpacing: true,
    endOfLine: 'lf',
    ignorePatterns: [
      '**/.next/**',
      '**/.output/**',
      '**/.turbo/**',
      '**/dist/**',
      '**/dev-dist/**',
      '**/node_modules/**',
      '**/routeTree.gen.ts',
      '**/.expo/**',
      '**/.wrangler/**',
      '**/.source/**',
      '**/coverage/**',
      '**/build/**',
      'apps/web/public/**',
      'bun.lock',
      'bun.lockb',
      'packages/brand/dist/**',
      '**/*.tsbuildinfo',
    ],
  },
  lint: {
    plugins: [
      'typescript',
      'react',
      'jsx-a11y',
      'import',
      'unicorn',
      'oxc',
      'promise',
    ],
    categories: {
      correctness: 'error',
      suspicious: 'error',
      perf: 'off',
      pedantic: 'off',
      style: 'off',
      restriction: 'off',
      nursery: 'off',
    },
    rules: {
      'jsx-a11y/no-static-element-interactions': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/no-array-index-key': 'off',
      'react-perf/jsx-no-new-object-as-prop': 'off',
      'react-perf/jsx-no-new-array-as-prop': 'off',
      'react-perf/jsx-no-new-function-as-prop': 'off',
      'react/jsx-no-constructed-context-values': 'off',
      'unicorn/no-array-sort': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'import/no-unassigned-import': 'off',
      'import/no-named-as-default': 'off',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    ignorePatterns: [
      '**/.next/**',
      '**/.output/**',
      '**/.turbo/**',
      '**/dist/**',
      '**/dev-dist/**',
      '**/node_modules/**',
      '**/routeTree.gen.ts',
      '**/.expo/**',
      '**/.wrangler/**',
      '**/.source/**',
      '**/.zed/**',
      '**/.vscode/**',
      '**/coverage/**',
      '**/build/**',
      '**/*.tsbuildinfo',
      'apps/web/public/**',
      'bun.lock',
      'bun.lockb',
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
  },
  staged: {
    '*.{js,jsx,ts,tsx,mjs,cjs}': 'vp check --fix',
    '*.{json,jsonc,md,mdx,css,scss,yaml,yml,html,toml}': 'vp fmt --write',
  },
});
